import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import { getFirestore, collection, addDoc, doc, setDoc, deleteDoc, onSnapshot, query, orderBy, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyA1hWwkHhv1RDG1915gEsjhaHIhUlGQjaU",authDomain:"trainingsplatz-sv-buckenhofen.firebaseapp.com",projectId:"trainingsplatz-sv-buckenhofen",storageBucket:"trainingsplatz-sv-buckenhofen.firebasestorage.app",messagingSenderId:"1098431238396",appId:"1:1098431238396:web:0c616849662d9ebe950779",measurementId:"G-XZNSZD7G4N"};
const OFFICIAL_LOGO="https://app.bfv.de/export.media/-/action/getLogo/format/7/id/00ES8GNKR800000NVV0AG08LVUPGND5I/verband/00ES8GNCQK000000VV0AG08LVUPGND5I/strat_code/bfv";
document.querySelectorAll('.official-logo').forEach(img=>{img.src=OFFICIAL_LOGO;img.onerror=()=>{img.onerror=null;img.src='icon.svg'}});

const TEAMS=[
{id:'H1',name:'Herren I',short:'H1',c:'#d20a11'},{id:'H2',name:'Herren II',short:'H2',c:'#8f0b12'},{id:'AH',name:'Alte Herren · AH',short:'AH',c:'#4b5563'},
{id:'A',name:'U19 · A-Junioren',short:'U19',c:'#1d4ed8'},{id:'B',name:'U17 · B-Junioren',short:'U17',c:'#0891b2'},{id:'C',name:'U15 · C-Junioren',short:'U15',c:'#15803d'},{id:'D',name:'U13 · D-Junioren',short:'U13',c:'#f97316'},
{id:'E',name:'U11 · E-Junioren',short:'U11',c:'#c99a00'},{id:'F',name:'U9 · F-Junioren',short:'U9',c:'#db2777'},{id:'G',name:'U7 · G-Junioren / Bambini',short:'U7',c:'#7c3aed'},
{id:'FS',name:'Fußballschule',short:'FS',c:'#7c5b3a'},{id:'V',name:'Verein / Verwaltung',short:'SVB',c:'#111827'}
];
const TYPES=[['training','Training'],['schule','Fußballschule / Sondertraining'],['liga','Ligaspiel'],['pokal','Pokalspiel'],['freundschaft','Freundschaftsspiel'],['turnier','Turnier / Kinderfestival'],['pflege','Platzpflege'],['sperre','Platz gesperrt'],['event','Vereinstermin / Event']];
const FIELDS=[['A1','A-Platz · Hälfte 1'],['A2','A-Platz · Hälfte 2'],['A','A-Platz · komplett'],['B1','B-Platz · Hälfte 1'],['B2','B-Platz · Hälfte 2'],['B','B-Platz · komplett'],['C','C-Platz · Trainingsfläche (halber Platz, ohne Tore)'],['none','Ohne Platz']];
const FIELD_COLS=['A1','A2','B1','B2','C'];
let app,auth,db,unsubscribe=null,events=[],currentMonday=getMonday(new Date()),activeTeam='ALL';
let planDayCount=14,boardDayCount=21,planObserver=null;
let settings={name:localStorage.getItem('svb_name')||'',defaultTeam:localStorage.getItem('svb_default_team')||'D'};
const DEFAULT_CONFIG={admins:['Stefan'],trainers:{D:['Stefan','Holger','Bülent']}};let appConfig=structuredClone(DEFAULT_CONFIG),weekMode='plan';
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function getMonday(d){d=new Date(d);d.setHours(12,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d}function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}function isoDate(d){return d.toISOString().slice(0,10)}
function fmtDate(s,opts={weekday:'short',day:'2-digit',month:'2-digit'}){return new Intl.DateTimeFormat('de-DE',opts).format(new Date(s+'T12:00:00'))}function fmtFull(d){return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d)}
function teamBy(id){return TEAMS.find(t=>t.id===id)||TEAMS.at(-1)}function minOf(t){const [h,m]=t.split(':').map(Number);return h*60+m}function overlaps(a1,a2,b1,b2){return a1<b2&&b1<a2}function isGame(t){return ['liga','pokal','freundschaft','turnier'].includes(t)}function typeLabel(id){return TYPES.find(x=>x[0]===id)?.[1]||id}function fieldLabel(id){return FIELDS.find(x=>x[0]===id)?.[1]||id}
function cabinLabel(v){return ({ja:'Kabine',keine:'keine Kabine','1':'1 Kabine','2':'2 Kabinen',mehr:'Sonder-Kabinen',unklar:'Kabinen offen'})[v]||''}function statusLabel(v){return ({fix:'Fix',verschoben:'Verschoben',vorlaeufig:'Vorläufig',abgesagt:'Abgesagt'})[v]||v||'Fix'}
function fieldConflict(a,b){if(a==='none'||b==='none')return false;if(a[0]!==b[0])return false;if(a.length===1||b.length===1)return true;return a===b}
function normName(v){return String(v||'').trim().toLocaleLowerCase('de-DE')}
function isAdminName(name=settings.name){return (appConfig.admins||[]).some(a=>normName(a)===normName(name))}
function defaultTrainerForTeam(team){return (appConfig.trainers?.[team]||[]).join(', ')}
function derivedTitle(e){const custom=String(e.title||'').trim();if(custom)return custom;const t=teamBy(e.team);if(e.type==='training')return `${t.short} · Training`;if(e.type==='schule')return `${t.short} · Fußballschule`;if(isGame(e.type)){if(e.opponent)return e.venueType==='auswaerts'?`${e.opponent} – ${t.short}`:`${t.short} – ${e.opponent}`;return `${t.short} · ${typeLabel(e.type)}`}return typeLabel(e.type)}
function easterSunday(y){let a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),month=Math.floor((h+l-7*m+114)/31),day=((h+l-7*m+114)%31)+1;return new Date(y,month-1,day,12)}
function dateAddISO(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return isoDate(x)}
function publicHolidays(y){const es=easterSunday(y),fixed=[[`${y}-01-01`,'Neujahr'],[`${y}-01-06`,'Heilige Drei Könige'],[`${y}-05-01`,'Tag der Arbeit'],[`${y}-08-15`,'Mariä Himmelfahrt · Forchheim'],[`${y}-10-03`,'Tag der Deutschen Einheit'],[`${y}-11-01`,'Allerheiligen'],[`${y}-12-25`,'1. Weihnachtstag'],[`${y}-12-26`,'2. Weihnachtstag']];return Object.fromEntries([...fixed,[dateAddISO(es,-2),'Karfreitag'],[dateAddISO(es,1),'Ostermontag'],[dateAddISO(es,39),'Christi Himmelfahrt'],[dateAddISO(es,50),'Pfingstmontag'],[dateAddISO(es,60),'Fronleichnam']])}
const SCHOOL_HOLIDAYS=[
['2026-08-03','2026-09-14','Sommerferien'],['2026-11-02','2026-11-06','Allerheiligenferien'],['2026-12-24','2027-01-08','Weihnachtsferien'],['2027-02-08','2027-02-12','Frühjahrsferien'],['2027-03-22','2027-04-02','Osterferien'],['2027-05-18','2027-05-28','Pfingstferien'],['2027-08-02','2027-09-13','Sommerferien']
];
function dateInfo(date){const h=publicHolidays(Number(date.slice(0,4)))[date]||'';const s=SCHOOL_HOLIDAYS.find(r=>date>=r[0]&&date<=r[1]);return{holiday:h,school:s?.[2]||''}}
function calendarBadges(date){const i=dateInfo(date),a=[];if(i.holiday)a.push(`<span class="calendar-badge holiday">${esc(i.holiday)}</span>`);if(i.school)a.push(`<span class="calendar-badge school">${esc(i.school)}</span>`);return a.join('')}
function dayWindow(date){const dow=new Date(date+'T12:00:00').getDay();return (dow===0||dow===6)?['09:00','22:00']:['14:00','22:00']}
function seasonEnd(date,season){const d=new Date(date+'T12:00:00'),y=d.getFullYear(),m=d.getMonth()+1;if(season==='autumn')return `${y}-11-30`;if(season==='winter')return `${m>=12?y+1:y}-02-${new Date(m>=12?y+1:y,2,0).getDate()}`;return `${y}-07-31`}
function suggestSeason(date){const m=Number(date.slice(5,7));return m>=8&&m<=11?'autumn':(m===12||m<=2)?'winter':'summer'}
function seed(){
  $('team').innerHTML=TEAMS.map(t=>`<option value="${t.id}">${t.name}</option>`).join('');$('icsTeam').innerHTML=$('team').innerHTML;$('defaultTeam').innerHTML=$('team').innerHTML;$('type').innerHTML=TYPES.map(t=>`<option value="${t[0]}">${t[1]}</option>`).join('');$('field').innerHTML=FIELDS.map(f=>`<option value="${f[0]}">${f[1]}</option>`).join('');
  renderAdminConfig();renderCalendarInfo();applyRoleUI();
  $('teamFilters').innerHTML=`<button class="team-pill active" data-team="ALL">Alle Teams</button>`+TEAMS.map(t=>`<button class="team-pill" data-team="${t.id}" style="--team:${t.c}"><i></i>${t.short}</button>`).join('');
  $('legend').innerHTML=TEAMS.map(t=>`<span class="legend-item" style="--team:${t.c}"><i></i>${t.name}</span>`).join('');
  document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{activeTeam=b.dataset.team;document.querySelectorAll('[data-team]').forEach(x=>x.classList.toggle('active',x===b));renderAll()});
}
function renderAdminConfig(){if(!$('trainerRows'))return;$('trainerRows').innerHTML=TEAMS.filter(t=>!['V'].includes(t.id)).map(t=>`<div class="trainer-row"><label>${esc(t.name)}</label><input data-trainer-team="${t.id}" value="${esc((appConfig.trainers?.[t.id]||[]).join(', '))}" placeholder="Trainername(n)" /></div>`).join('');$('adminNames').value=(appConfig.admins||[]).join(', ');const names=new Set();Object.values(appConfig.trainers||{}).flat().forEach(n=>names.add(n));(appConfig.admins||[]).forEach(n=>names.add(n));$('trainerNames').innerHTML=[...names].sort().map(n=>`<option value="${esc(n)}"></option>`).join('')}
function applyRoleUI(){if(!$('adminNav'))return;$('adminNav').classList.toggle('hidden',!isAdminName())}
function renderCalendarInfo(){if(!$('calendarInfo'))return;const now=new Date(),y=now.getFullYear(),hol=Object.entries(publicHolidays(y)).filter(([d])=>d>=isoDate(now)).sort().slice(0,8);let html='<div class="holiday-line"><b>Schuljahr</b><span>2026/27 · Ferien werden im Wochen- und Monatsplan markiert, ändern aber keine Serientermine automatisch.</span></div>';for(const [a,b,n] of SCHOOL_HOLIDAYS.filter(r=>r[1]>=isoDate(now)).slice(0,8))html+=`<div class="holiday-line"><b>${fmtDate(a,{day:'2-digit',month:'2-digit'})}</b><span>${esc(n)} bis ${fmtDate(b,{day:'2-digit',month:'2-digit',year:'numeric'})}</span></div>`;for(const [d,n] of hol)html+=`<div class="holiday-line"><b>${fmtDate(d,{day:'2-digit',month:'2-digit'})}</b><span>${esc(n)}</span></div>`;$('calendarInfo').innerHTML=html}
function filteredForRange(start,end){return events.filter(e=>e.date>=start&&e.date<=end&&(activeTeam==='ALL'||e.team===activeTeam))}
function updateHero(){const start=isoDate(currentMonday),end=isoDate(addDays(currentMonday,6)),es=filteredForRange(start,end);$('heroTrainings').textContent=es.filter(e=>['training','schule'].includes(e.type)).length;$('heroGames').textContent=es.filter(e=>isGame(e.type)&&e.venueType!=='auswaerts').length;$('heroBlocks').textContent=es.filter(e=>['pflege','sperre'].includes(e.type)).length;$('weekRange').textContent=`${fmtFull(currentMonday)} – ${fmtFull(addDays(currentMonday,6))}`}
function eventClass(e){return `event-block ${e.field.length===1?'full':''} ${isGame(e.type)?'game':''} ${['pflege','sperre'].includes(e.type)?'block':''} ${e.status==='verschoben'?'changed':''}`}
function eventHTML(e){const t=teamBy(e.team);const status=e.status&&e.status!=='fix'?`<span class="status-tag ${e.status==='abgesagt'?'cancel':''}">${esc(statusLabel(e.status).toUpperCase())}</span>`:'';const opp=e.opponent?` · ${esc(e.opponent)}`:'';return `<strong>${status}${esc(e.start)} ${esc(derivedTitle(e))}</strong><div class="event-meta">${esc(fieldLabel(e.field))}${e.trainer?' · '+esc(e.trainer):''}${opp}${e.cabins&&e.cabins!=='keine'?' · '+esc(cabinLabel(e.cabins)):''}</div>`}
function renderDay(date){
  const dateISO=isoDate(date),today=isoDate(new Date()),[dayStart,dayEnd]=dayWindow(dateISO),startMin=minOf(dayStart),endMin=minOf(dayEnd),slotCount=Math.max(1,Math.ceil((endMin-startMin)/30));
  const es=events.filter(e=>e.date===dateISO&&(activeTeam==='ALL'||e.team===activeTeam));const placed=es.filter(e=>e.field!=='none'),noplace=es.filter(e=>e.field==='none');
  const wrap=document.createElement('div');wrap.className='day-card';const dayTitle=document.createElement('div');dayTitle.className='day-title'+(dateISO===today?' today':'');dayTitle.innerHTML=`<span class="day-name">${fmtDate(dateISO,{weekday:'long'})}</span><span class="day-date">${fmtDate(dateISO,{day:'2-digit',month:'2-digit',year:'numeric'})}</span><span class="calendar-badges">${calendarBadges(dateISO)}</span><span class="day-badge">${es.length} Termin${es.length===1?'':'e'}</span>`;wrap.appendChild(dayTitle);
  const grid=document.createElement('div');grid.className='field-grid';grid.innerHTML=`<div class="field-head time">Zeit</div>${FIELD_COLS.map(f=>`<div class="field-head"><b>${f==='C'?'C-Platz':f[0]+'-Platz'}</b><span>${f==='C'?'Training · ohne Tore':(f.endsWith('1')?'Hälfte 1':'Hälfte 2')}</span></div>`).join('')}`;
  for(let i=0;i<slotCount;i++){const m=startMin+i*30,h=String(Math.floor(m/60)).padStart(2,'0'),mm=String(m%60).padStart(2,'0');const tc=document.createElement('div');tc.className='time-cell';tc.textContent=`${h}:${mm}`;tc.style.gridColumn='1';tc.style.gridRow=String(i+2);grid.appendChild(tc);FIELD_COLS.forEach((f,j)=>{const cell=document.createElement('div');cell.className='field-cell';cell.style.gridColumn=String(j+2);cell.style.gridRow=String(i+2);cell.onclick=()=>openNew({date:dateISO,start:`${h}:${mm}`,end:minutesToTime(m+90),field:f});grid.appendChild(cell)})}
  const colMap={A1:'2 / 3',A2:'3 / 4',A:'2 / 4',B1:'4 / 5',B2:'5 / 6',B:'4 / 6',C:'6 / 7'};
  placed.forEach(e=>{const sm=Math.max(startMin,minOf(e.start)),em=Math.min(endMin,minOf(e.end));if(em<=startMin||sm>=endMin)return;const startRow=2+Math.floor((sm-startMin)/30),span=Math.max(1,Math.ceil((em-sm)/30));const chip=document.createElement('div');chip.className=eventClass(e);chip.style.setProperty('--team',teamBy(e.team).c);chip.style.gridColumn=colMap[e.field]||'2 / 3';chip.style.gridRow=`${startRow} / span ${span}`;chip.innerHTML=eventHTML(e);chip.onclick=()=>openEdit(e);grid.appendChild(chip)});wrap.appendChild(grid);
  if(noplace.length){const n=document.createElement('div');n.className='no-place';n.innerHTML='<div class="no-place-title">Ohne Platz / Vereinsinfo</div>'+noplace.map(e=>`<div class="no-place-item" data-id="${e.id}" style="--team:${teamBy(e.team).c}"><b>${e.start} · ${derivedTitle(e)}</b><span>${teamBy(e.team).name} · ${typeLabel(e.type)}</span></div>`).join('');wrap.appendChild(n);n.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>openEdit(events.find(e=>e.id===x.dataset.id)))}
  return wrap;
}
function addPlanSentinel(){const more=document.createElement('div');more.id='planMore';more.className='scroll-more';more.textContent='Weiter scrollen – weitere Tage werden automatisch geladen';$('weekDays').appendChild(more);if(planObserver)planObserver.disconnect();planObserver=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)&&weekMode==='plan'){planObserver.disconnect();appendPlanDays(14)}},{root:null,rootMargin:'700px'});planObserver.observe(more)}
function appendPlanDays(count=14){const root=$('weekDays'),old=$('planMore');if(old)old.remove();const start=planDayCount;for(let i=0;i<count;i++)root.appendChild(renderDay(addDays(currentMonday,start+i)));planDayCount+=count;addPlanSentinel()}
function renderWeek(){
  const boardLeft=$('weekBoard')?.scrollLeft||0;
  $('weekDays').innerHTML='';for(let i=0;i<planDayCount;i++)$('weekDays').appendChild(renderDay(addDays(currentMonday,i)));addPlanSentinel();renderWeekBoard(boardLeft);updateHero();applyWeekMode()
}
function makeWeekBoardDay(d){const today=isoDate(new Date()),date=isoDate(d),es=events.filter(e=>e.date===date&&(activeTeam==='ALL'||e.team===activeTeam)).sort((a,b)=>a.start.localeCompare(b.start));const col=document.createElement('div');col.className='week-board-day';col.innerHTML=`<div class="week-board-head ${date===today?'today':''}"><b>${fmtDate(date,{weekday:'long'})}</b><small>${fmtDate(date,{day:'2-digit',month:'2-digit'})} · ${dayWindow(date)[0]}–22:00 ${calendarBadges(date)}</small></div><div class="week-board-events">${es.length?es.map(e=>`<div class="week-board-event" data-id="${esc(e.id)}" style="--team:${teamBy(e.team).c}"><b>${esc(e.start)}–${esc(e.end)} · ${esc(derivedTitle(e))}</b><span>${esc(fieldLabel(e.field))}${e.trainer?' · '+esc(e.trainer):''}</span></div>`).join(''):'<div class="week-board-empty">frei / keine Termine</div>'}</div>`;col.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>openEdit(events.find(e=>e.id===x.dataset.id)));return col}
function appendBoardDays(count=14){const start=boardDayCount;for(let i=0;i<count;i++)$('weekBoard').appendChild(makeWeekBoardDay(addDays(currentMonday,start+i)));boardDayCount+=count}
function renderWeekBoard(restoreLeft=0){$('weekBoard').innerHTML='';for(let i=0;i<boardDayCount;i++)$('weekBoard').appendChild(makeWeekBoardDay(addDays(currentMonday,i)));requestAnimationFrame(()=>{$('weekBoard').scrollLeft=restoreLeft})}
function applyWeekMode(){$('weekDays').classList.toggle('hidden',weekMode!=='plan');$('weekBoard').classList.toggle('hidden',weekMode!=='board');$('planModeBtn').classList.toggle('active',weekMode==='plan');$('boardModeBtn').classList.toggle('active',weekMode==='board')}

function renderMonth(){const base=addDays(currentMonday,3),start=new Date(base.getFullYear(),base.getMonth(),1),end=new Date(base.getFullYear(),base.getMonth()+1,0),es=filteredForRange(isoDate(start),isoDate(end)).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start));$('monthLabel').textContent=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(start);if(!es.length){$('monthList').innerHTML='<div class="hint">In diesem Monat sind noch keine Termine eingetragen.</div>';return}let html='',last='';for(const e of es){if(e.date!==last){html+=`<div class="month-day">${fmtDate(e.date,{weekday:'long',day:'2-digit',month:'long'})}${calendarBadges(e.date)}</div>`;last=e.date}const t=teamBy(e.team);html+=`<div class="list-item" data-id="${e.id}"><i class="list-stripe" style="--team:${t.c}"></i><div class="list-main"><b>${e.start}–${e.end} · ${derivedTitle(e)}</b><small>${t.name} · ${fieldLabel(e.field)}${e.trainer?' · '+e.trainer:''} · ${statusLabel(e.status)}${e.updatedBy?' · zuletzt '+e.updatedBy:''}</small></div><div class="chev">›</div></div>`}$('monthList').innerHTML=html;$('monthList').querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>openEdit(events.find(e=>e.id===x.dataset.id)))}
function durationHours(e){return Math.max(0,(minOf(e.end)-minOf(e.start))/60)}
function overviewItem(e,kind=''){const t=teamBy(e.team),tag=kind==='game'?'Heimspiel':kind==='changed'?'Geändert':kind==='event'?'Info':typeLabel(e.type);return `<div class="overview-item ${kind}" data-id="${esc(e.id)}" style="--team:${t.c}"><i class="mark"></i><div class="copy"><b>${esc(fmtDate(e.date,{weekday:'short',day:'2-digit',month:'2-digit'}))} · ${esc(e.start)}–${esc(e.end)} · ${esc(derivedTitle(e))}</b><small>${esc(t.name)}${e.trainer?' · '+esc(e.trainer):''} · ${esc(fieldLabel(e.field))}${e.opponent?' · '+esc(e.opponent):''}${e.updatedBy?' · geändert von '+esc(e.updatedBy):''}${e.changeReason?' · '+esc(e.changeReason):''}</small></div><span class="tag">${esc(tag)}</span></div>`}
function bindOverview(container){container.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>openEdit(events.find(e=>e.id===x.dataset.id)))}
function renderStats(){const start=isoDate(getMonday(new Date())),end=isoDate(addDays(getMonday(new Date()),6)),es=events.filter(e=>e.date>=start&&e.date<=end),future=events.filter(e=>e.date>=isoDate(new Date()));const aHours=es.filter(e=>e.field&&e.field.startsWith('A')).reduce((n,e)=>n+durationHours(e)*(e.field==='A'?2:1),0)/2,bHours=es.filter(e=>e.field&&e.field.startsWith('B')).reduce((n,e)=>n+durationHours(e)*(e.field==='B'?2:1),0)/2,cHours=es.filter(e=>e.field==='C').reduce((n,e)=>n+durationHours(e),0);$('stats').innerHTML=`<div class="info-stat"><b>${es.length}</b><span>Termine diese Woche</span></div><div class="info-stat"><b>${es.filter(e=>isGame(e.type)&&e.venueType!=='auswaerts').length}</b><span>Heimspiele</span></div><div class="info-stat"><b>${aHours.toFixed(1).replace('.0','')} h</b><span>A-Platz gebucht</span></div><div class="info-stat"><b>${bHours.toFixed(1).replace('.0','')} h</b><span>B-Platz gebucht</span></div><div class="info-stat"><b>${cHours.toFixed(1).replace('.0','')} h</b><span>C-Fläche gebucht</span></div>`;const home= future.filter(e=>isGame(e.type)&&e.venueType!=='auswaerts').sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)).slice(0,8);$('homeGames').innerHTML=home.length?home.map(e=>overviewItem(e,'game')).join(''):'<div class="overview-empty">Noch keine kommenden Heimspiele eingetragen.</div>';bindOverview($('homeGames'));const changes=future.filter(e=>e.status==='verschoben'||e.status==='abgesagt'||e.changeReason||e.previousSlot).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)).slice(0,10);$('changesList').innerHTML=changes.length?changes.map(e=>overviewItem(e,'changed')).join(''):'<div class="overview-empty">Aktuell keine gemeldeten Änderungen.</div>';bindOverview($('changesList'));const specials=future.filter(e=>['pflege','sperre','event'].includes(e.type)).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)).slice(0,10);$('clubEvents').innerHTML=specials.length?specials.map(e=>overviewItem(e,'event')).join(''):'<div class="overview-empty">Keine kommenden Sperren oder Sondertermine.</div>';bindOverview($('clubEvents'))}
function renderAll(){renderWeek();renderMonth();renderStats()}
function minutesToTime(m){m=((m%1440)+1440)%1440;return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
function openNew(pref={}){$('modalTitle').textContent='Termin eintragen';$('eventForm').reset();$('eventId').value='';$('deleteBtn').classList.add('hidden');$('seriesTools').classList.add('hidden');$('quickMoveWrap').classList.add('hidden');$('auditBox').classList.add('hidden');$('editorName').value=settings.name;$('date').value=pref.date||isoDate(new Date());$('start').value=pref.start||'17:00';$('end').value=pref.end||'18:30';$('team').value=pref.team||settings.defaultTeam||'D';$('type').value='training';$('field').value=pref.field||'A1';$('status').value='fix';$('venueType').value='heim';$('cabins').value='unklar';$('trainer').value=defaultTrainerForTeam($('team').value)||settings.name;syncTypeFields();$('eventDialog').showModal()}
function openEdit(e){$('modalTitle').textContent='Termin bearbeiten';$('eventId').value=e.id;for(const k of ['type','team','title','date','start','end','field','opponent','cabins','note','changeReason','status','venueType','trainer'])if($(k))$(k).value=e[k]||({status:'fix',venueType:'heim',cabins:'unklar'}[k]||'');$('trainer').value=e.trainer||defaultTrainerForTeam(e.team)||e.createdBy||'';$('editorName').value=settings.name||e.updatedBy||e.createdBy||'';$('repeatWeekly').checked=false;$('repeatUntilWrap').classList.add('hidden');$('deleteBtn').classList.remove('hidden');$('seriesTools').classList.toggle('hidden',!e.seriesId);$('quickMoveWrap').classList.remove('hidden');const audit=[];if(e.createdBy)audit.push('Eingetragen von '+e.createdBy);if(e.updatedBy)audit.push('zuletzt geändert von '+e.updatedBy);if(e.previousSlot)audit.push('vorher: '+e.previousSlot);if(e.changeReason)audit.push('Grund: '+e.changeReason);$('auditBox').textContent=audit.join(' · ');$('auditBox').classList.toggle('hidden',!audit.length);syncTypeFields();$('eventDialog').showModal()}
function syncTypeFields(){const game=isGame($('type').value);if(game){const cur=$('field').value;if(!['A','B','none'].includes(cur))$('field').value=cur.startsWith('B')?'B':'A'}[...$('field').options].forEach(o=>o.disabled=game&&!['A','B','none'].includes(o.value));if($('type').value==='event')$('field').value='none'}
function findConflicts(c,ignore=''){return events.filter(e=>e.id!==ignore&&e.date===c.date&&fieldConflict(e.field,c.field)&&overlaps(minOf(e.start),minOf(e.end),minOf(c.start),minOf(c.end)))}
async function saveOne(data,id=null){data.updatedAt=serverTimestamp();data.updatedBy=(data.updatedBy||$('editorName')?.value||settings.name||'System').trim();if(id)await setDoc(doc(db,'events',id),data,{merge:true});else await addDoc(collection(db,'events'),{...data,createdAt:serverTimestamp(),createdBy:data.updatedBy})}
$('eventForm').onsubmit=async ev=>{ev.preventDefault();if(!db)return alert('Firebase ist noch nicht verbunden.');const keys=['type','team','title','date','start','end','field','opponent','cabins','note','changeReason','status','venueType','trainer'],data={};for(const k of keys)data[k]=$(k).value.trim?.()??$(k).value;data.updatedBy=$('editorName').value.trim();if(!data.trainer)return alert('Bitte Trainer / verantwortliche Person angeben.');if(!data.updatedBy)return alert('Bitte deinen Namen bei „eingetragen / geändert von“ angeben.');if(minOf(data.end)<=minOf(data.start))return alert('Endzeit muss nach der Startzeit liegen.');if((minOf(data.start)%30)||(minOf(data.end)%30))if(!confirm('Die Zeit liegt nicht genau im 30-Minuten-Raster. Trotzdem speichern?'))return;if(isGame(data.type)&&!['A','B','none'].includes(data.field))return alert('Spiele belegen immer den kompletten A- oder B-Platz.');if(data.venueType==='auswaerts'&&data.field!=='none'&&!confirm('Das Spiel ist als Auswärtsspiel markiert, belegt aber einen SVB-Platz. Trotzdem speichern?'))return;const editId=$('eventId').value,existing=events.find(e=>e.id===editId);if(existing&&(existing.date!==data.date||existing.start!==data.start||existing.end!==data.end||existing.field!==data.field)){data.previousSlot=`${fmtDate(existing.date,{day:'2-digit',month:'2-digit',year:'numeric'})} · ${existing.start}–${existing.end} · ${fieldLabel(existing.field)}`;if(!data.changeReason)data.changeReason='Termin verschoben / Platz geändert'}const conflicts=findConflicts(data,editId);if(conflicts.length&&!confirm(`Platzkonflikt mit ${conflicts.length} Termin(en):\n${conflicts.map(c=>derivedTitle(c)+' '+c.start+'–'+c.end).join('\n')}\n\nTrotzdem speichern?`))return;settings.name=data.updatedBy;localStorage.setItem('svb_name',settings.name);try{if($('repeatWeekly').checked&&!editId){if(!$('repeatUntil').value)return alert('Bitte Enddatum wählen.');const seriesId=(crypto.randomUUID?.()||('serie-'+Date.now()+'-'+Math.random().toString(36).slice(2)));let d=new Date(data.date+'T12:00:00'),end=new Date($('repeatUntil').value+'T12:00:00'),count=0;while(d<=end&&count<60){await saveOne({...data,date:isoDate(d),seriesId,seriesNo:count+1});d=addDays(d,7);count++}}else await saveOne(data,editId||null);$('eventDialog').close()}catch(err){alert('Speichern fehlgeschlagen: '+err.message)}};
$('deleteBtn').onclick=async()=>{const id=$('eventId').value;if(id&&confirm('Nur diesen Termin wirklich löschen?')){await deleteDoc(doc(db,'events',id));$('eventDialog').close()}};$('deleteFutureBtn').onclick=async()=>{const id=$('eventId').value,e=events.find(x=>x.id===id);if(!e?.seriesId)return;if(!confirm('Diesen und alle folgenden Termine dieser Serie löschen?'))return;const targets=events.filter(x=>x.seriesId===e.seriesId&&x.date>=e.date);for(const x of targets)await deleteDoc(doc(db,'events',x.id));$('eventDialog').close()};$('cancelBtn').onclick=()=>$('eventDialog').close();$('closeDialog').onclick=()=>$('eventDialog').close();$('type').onchange=syncTypeFields;$('venueType').onchange=()=>{if($('venueType').value==='auswaerts')$('field').value='none'};$('repeatWeekly').onchange=()=>{const on=$('repeatWeekly').checked;$('repeatUntilWrap').classList.toggle('hidden',!on);if(on&&!$('repeatUntil').value)$('repeatUntil').value=seasonEnd($('date').value,suggestSeason($('date').value))};document.querySelectorAll('[data-season]').forEach(b=>b.onclick=()=>$('repeatUntil').value=seasonEnd($('date').value,b.dataset.season));$('team').onchange=()=>{if(!$('eventId').value)$('trainer').value=defaultTrainerForTeam($('team').value)||$('trainer').value||settings.name};
function switchView(v){if(v==='admin'&&!isAdminName())return alert('Adminbereich ist für diesen Namen nicht freigeschaltet.');$('weekView').classList.toggle('hidden',v!=='week');$('monthView').classList.toggle('hidden',v!=='month');$('infoView').classList.toggle('hidden',v!=='info');$('adminView').classList.toggle('hidden',v!=='admin');document.querySelectorAll('.nav-btn[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}document.querySelectorAll('.nav-btn[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('planModeBtn').onclick=()=>{weekMode='plan';applyWeekMode();setTimeout(()=>{const m=$('planMore');if(m&&planObserver)planObserver.observe(m)},0)};$('boardModeBtn').onclick=()=>{weekMode='board';applyWeekMode()};$('weekBoard').addEventListener('scroll',()=>{const el=$('weekBoard');if(weekMode==='board'&&el.scrollLeft+el.clientWidth>=el.scrollWidth-650)appendBoardDays(14)},{passive:true});
$('navNew').onclick=()=>openNew();$('newBtn').onclick=()=>openNew();function resetContinuousRange(){planDayCount=14;boardDayCount=21;if(planObserver)planObserver.disconnect()}$('prevBtn').onclick=()=>{currentMonday=addDays(currentMonday,-7);resetContinuousRange();renderAll()};$('nextBtn').onclick=()=>{currentMonday=addDays(currentMonday,7);resetContinuousRange();renderAll()};$('todayBtn').onclick=()=>{currentMonday=getMonday(new Date());resetContinuousRange();switchView('week');renderAll()};
$('settingsBtn').onclick=()=>{$('myName').value=settings.name;$('defaultTeam').value=settings.defaultTeam;$('settingsDialog').showModal()};$('closeSettings').onclick=()=>$('settingsDialog').close();$('saveSettings').onclick=()=>{settings.name=$('myName').value.trim();settings.defaultTeam=$('defaultTeam').value;localStorage.setItem('svb_name',settings.name);localStorage.setItem('svb_default_team',settings.defaultTeam);$('settingsDialog').close();applyRoleUI();renderAll()};
$('saveAdminConfig').onclick=async()=>{if(!db)return alert('Firebase noch nicht verbunden.');const trainers={};document.querySelectorAll('[data-trainer-team]').forEach(i=>{trainers[i.dataset.trainerTeam]=i.value.split(',').map(x=>x.trim()).filter(Boolean)});const admins=$('adminNames').value.split(',').map(x=>x.trim()).filter(Boolean);appConfig={admins,trainers};await setDoc(doc(db,'events','_svb_config'),{isConfig:true,date:'0000-01-01',start:'00:00',end:'00:00',field:'none',team:'V',type:'event',title:'SVB Konfiguration',admins,trainers,updatedBy:settings.name||'Admin',updatedAt:serverTimestamp()},{merge:true});renderAdminConfig();applyRoleUI();alert('Grundeinstellungen gespeichert.')};
function shiftFormMinutes(delta){$('start').value=minutesToTime(minOf($('start').value)+delta);$('end').value=minutesToTime(minOf($('end').value)+delta);$('status').value='verschoben'}
function shiftFormDay(delta){const d=new Date($('date').value+'T12:00:00');d.setDate(d.getDate()+delta);$('date').value=isoDate(d);$('status').value='verschoben'}
document.querySelectorAll('[data-shift-min]').forEach(b=>b.onclick=()=>shiftFormMinutes(Number(b.dataset.shiftMin)));document.querySelectorAll('[data-shift-day]').forEach(b=>b.onclick=()=>shiftFormDay(Number(b.dataset.shiftDay)));$('switchFieldBtn').onclick=()=>{const f=$('field').value;if(f==='A')$('field').value='B';else if(f==='B')$('field').value='A';else if(f.startsWith('A'))$('field').value='B'+f.slice(1);else if(f.startsWith('B'))$('field').value='A'+f.slice(1);$('status').value='verschoben'};$('markMovedBtn').onclick=()=>{$('status').value='verschoben';if(!$('changeReason').value)$('changeReason').value='Termin verschoben'};
function exportCSV(){const head=['Datum','Von','Bis','Mannschaft','Art','Titel','Trainer/Verantwortlich','Platz','Heim/Auswärts','Gegner','Kabinen','Status','Geändert von','Änderungsgrund','Notiz'];const rows=events.slice().sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)).map(e=>[e.date,e.start,e.end,teamBy(e.team).name,typeLabel(e.type),e.title||'',e.trainer||'',fieldLabel(e.field),e.venueType||'',e.opponent||'',cabinLabel(e.cabins),statusLabel(e.status),e.updatedBy||'',e.changeReason||'',e.note||'']);const q=v=>'"'+String(v??'').replaceAll('\"','\"\"')+'"';const csv='\ufeff'+[head,...rows].map(r=>r.map(q).join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='SVB-Platzplan-'+isoDate(new Date())+'.csv';a.click();URL.revokeObjectURL(a.href)}$('exportCsvBtn').onclick=exportCSV;
async function importICS(){const file=$('icsFile').files[0];if(!file)return alert('Bitte zuerst eine .ics-Datei wählen.');const txt=await file.text(),blocks=txt.split('BEGIN:VEVENT').slice(1).map(x=>x.split('END:VEVENT')[0]);let imported=0;for(const b of blocks){const lines=b.split(/\r?\n/),get=key=>{const line=lines.find(l=>l.startsWith(key));return line?line.split(':').slice(1).join(':').trim():''},ds=get('DTSTART'),de=get('DTEND'),sum=get('SUMMARY')||'BFV-Spiel',loc=get('LOCATION');if(!ds)continue;const parse=s=>{const z=s.replace(/[^0-9T]/g,''),date=z.slice(0,8),time=z.includes('T')?z.slice(9,13):'1200';return{date:`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}`,time:`${time.slice(0,2)}:${time.slice(2,4)}`}};const a=parse(ds),z=de?parse(de):{time:minutesToTime(minOf(a.time)+120)},home=/SV Buckenhofen/i.test(sum)&&!new RegExp('[-–]\\s*SV Buckenhofen','i').test(sum);await saveOne({type:'liga',team:$('icsTeam').value,title:sum,date:a.date,start:a.time,end:z.time,field:home?$('icsField').value:'none',opponent:'',trainer:defaultTrainerForTeam($('icsTeam').value)||settings.name||'SVB',cabins:home?'unklar':'keine',note:`Importiert aus BFV / ICS${loc?' · '+loc:''}`,changeReason:'BFV / ICS-Import',status:'fix',venueType:home?'heim':'auswaerts',updatedBy:settings.name||'BFV-Import'});imported++}alert(`${imported} Termine importiert.`)}$('importIcsBtn').onclick=importICS;
function parseCsvLine(line,sep=';'){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===sep&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out}
async function importCSV(){const file=$('csvFile').files[0];if(!file)return alert('Bitte CSV-Datei auswählen.');const text=(await file.text()).replace(/^\uFEFF/,'');const lines=text.split(/\r?\n/).filter(Boolean);if(lines.length<2)return alert('CSV enthält keine Daten.');const sep=lines[0].includes(';')?';':',';const head=parseCsvLine(lines[0],sep).map(x=>x.trim());const idx=n=>head.findIndex(h=>h.toLocaleLowerCase('de-DE')===n.toLocaleLowerCase('de-DE'));let count=0;for(const line of lines.slice(1)){const r=parseCsvLine(line,sep),get=n=>{const i=idx(n);return i>=0?(r[i]||'').trim():''};const teamName=get('Mannschaft'),typeName=get('Art'),fieldName=get('Platz');const team=TEAMS.find(t=>t.name===teamName||t.id===teamName||t.short===teamName)?.id||settings.defaultTeam;const type=TYPES.find(t=>t[1]===typeName||t[0]===typeName)?.[0]||'training';const field=FIELDS.find(f=>f[1]===fieldName||f[0]===fieldName)?.[0]||'none';const date=get('Datum');if(!date)continue;await saveOne({date,start:get('Von')||'17:00',end:get('Bis')||'18:30',team,type,title:get('Titel'),trainer:get('Trainer/Verantwortlich')||defaultTrainerForTeam(team)||settings.name||'SVB',field,venueType:get('Heim/Auswärts')||'heim',opponent:get('Gegner'),cabins:'unklar',status:'fix',changeReason:get('Änderungsgrund')||'CSV-Import',note:get('Notiz'),updatedBy:settings.name||'CSV-Import'});count++}alert(`${count} CSV-Termine importiert.`)}$('importCsvBtn').onclick=importCSV;
async function connect(){try{app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);await signInAnonymously(auth);onAuthStateChanged(auth,u=>{if(!u)return;$('syncStatus').textContent='Live synchronisiert · Änderungen sind sofort für alle Trainer sichtbar';$('syncStatus').className='sync online';const q=query(collection(db,'events'),orderBy('date','asc'));if(unsubscribe)unsubscribe();unsubscribe=onSnapshot(q,s=>{const all=s.docs.map(d=>({id:d.id,...d.data()}));const cfg=all.find(d=>d.isConfig||d.id==='_svb_config');if(cfg){appConfig={admins:cfg.admins||DEFAULT_CONFIG.admins,trainers:cfg.trainers||DEFAULT_CONFIG.trainers};renderAdminConfig();applyRoleUI()}events=all.filter(d=>!d.isConfig&&d.id!=='_svb_config');renderAll()},err=>{$('syncStatus').textContent='Firestore-Regeln prüfen';$('syncStatus').className='sync';console.error(err)})})}catch(err){$('syncStatus').textContent='Firebase nicht bereit';console.error(err)}}
seed();renderAll();connect();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
